#!/bin/bash
#
# Univention Maintenance
#  maintenance script
#
# Copyright 2004-2018 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

# Mrtg will most likely not work properly when the environment variable
# LANG is set to UTF-8.
export LANG=C

# Name of config file
configfile="/etc/univention/univention-maintenance.conf"

# Search config file and check values
test -e "$configfile" || {
    echo
    echo "ERROR: Config file \"$configfile\" was not found!"
    echo
    exit 2;
}

. "$configfile"

test -z "$mrtg_config" && touch "$mrtg_config" 2>/dev/null && {
    echo
    echo "ERROR: \"\$mrtg_config\" is not valid."
    echo
    exit 2;
}
test -z "$wwwdir" && mkdir -p "$wwwdir" 2>/dev/null && {
    echo
    echo "ERROR: Missing \"\$wwwdir\" in $configfile"
    echo
    exit 2;
}
test -z "$indexhtm" && {
    echo
    echo "ERROR: Missing \"\$indexhtm\" in $configfile"
    echo
    exit 2;
}

# Delete old mrtg files
rm -f "$wwwdir"/u{c,d}s_*.{png,txt}
find "$wwwdir" -name "uds_*.log" -exec bash -c 'mv "$0" "${0/\/uds/\/ucs}"' {} \;

# memory
freemem=$(</proc/meminfo grep -oP '^MemFree: *\K[0-9]+')
buffers=$(</proc/meminfo grep -oP '^Buffers: *\K[0-9]+')
cached=$(</proc/meminfo grep -oP '^Cached: *\K[0-9]+')
memtotal=$(</proc/meminfo grep -oP '^MemTotal: *\K[0-9]+')
free=$(($buffers + $cached + $freemem))
memused=$(($memtotal - $free))
prctmem=$((100 * $memused / $memtotal))
mrtgname="ucs_2mem"
cat <<__EOT__ >"$mrtg_config"
WorkDir: $wwwdir
Language: german
Interval: 15
Target[$mrtgname]: \`echo -e \"$prctmem\n0\nunused\nunused\"\`
Options[$mrtgname]: growright,noo,gauge,nobanner,noborder,nolegend,noinfo
Unscaled[$mrtgname]: dwmy
MaxBytes[$mrtgname]: 100
AbsMax[$mrtgname]: 99999
Title[$mrtgname]: 
Ylegend[$mrtgname]: % 
Colours[$mrtgname]: blau#6666ff,unused#000000,unused#000000,unused#000000
Background[$mrtgname]: #ffffff
PageTop[$mrtgname]: <H1>Speicherauslastung</H1>
__EOT__
mrtg "$mrtg_config" 2>/dev/null
rm -f "$wwwdir"/ucs_*.htm*
echo "Auslastung des Hauptspeichers: $prctmem%" >"$wwwdir/$mrtgname.txt"

# swap
swaptotal=$(</proc/meminfo grep -oP '^SwapTotal: *\K[0-9]+')
swapfree=$(</proc/meminfo grep -oP '^SwapFree: *\K[0-9]+')
swapused=$(($swaptotal - $swapfree))
if [ "$swaptotal" = "0" ]; then
	prctswap=0
else
	prctswap=$((100 * $swapused / $swaptotal)) 
fi
mrtgname="ucs_3swap"
cat <<__EOT__ >"$mrtg_config"
WorkDir: $wwwdir
Language: german
Interval: 15
Target[$mrtgname]: \`echo -e \"$prctswap\n0\nunused\nunused\"\`
Options[$mrtgname]: growright,noo,gauge,nobanner,noborder,nolegend,noinfo
Unscaled[$mrtgname]: dwmy
MaxBytes[$mrtgname]: 100
AbsMax[$mrtgname]: 99999
Title[$mrtgname]: 
Ylegend[$mrtgname]: %
Colours[$mrtgname]: blau#6666ff,unused#000000,unused#000000,unused#000000
Background[$mrtgname]: #ffffff
PageTop[$mrtgname]: <H1>Swapauslastung</H1>
__EOT__
mrtg "$mrtg_config" 2>/dev/null
rm -f "$wwwdir"/ucs_*.htm*
echo "Auslastung des Auslagerungsspeicher: $prctswap%" >"$wwwdir/$mrtgname.txt"

# CPU usage of last 15 minutes
loadavg=$(<<<"$(</proc/loadavg cut -d" " -f3)*100/1" bc)
mrtgname="ucs_0load"
cat <<__EOT__ >"$mrtg_config"
WorkDir: $wwwdir
Language: german
Interval: 15
Target[$mrtgname]: \`echo -e \"$loadavg\n0\nunused\nunused\"\`
Options[$mrtgname]: growright,noo,gauge,nobanner,noborder,nolegend,noinfo
Unscaled[$mrtgname]: dwmy
MaxBytes[$mrtgname]: 100
AbsMax[$mrtgname]: 99999
Title[$mrtgname]: 
Ylegend[$mrtgname]: %
Colours[$mrtgname]: blau#6666ff,unused#000000,unused#000000,unused#000000
Background[$mrtgname]: #ffffff
PageTop[$mrtgname]: <H1>Systemlast</H1>
__EOT__
mrtg "$mrtg_config" 2>/dev/null
rm -f "$mrtg_config" "$wwwdir"/ucs_*.htm*
echo "Systemlast: $loadavg%" >"$wwwdir/$mrtgname.txt"

# Write HTML file
cat <<__EOT__ >"$wwwdir/$indexhtm"
<HTML>
<HEAD>
</HEAD>
<BODY BGCOLOR="#F0F0F0">
__EOT__
for file in "$wwwdir"/*-day.png; do
    echo "<P ALIGN=\"center\"><FONT FACE=\"ARIAL\">"
    cat "${file%%-day.png}.txt"
    echo "<BR>"
    file="${file##*/}"
    echo "<IMG SRC=\"$file\"><BR>"
    echo "<IMG SRC=\"${file/%day.png/week.png}\"><BR>"
    echo "<IMG SRC=\"${file/%day.png/month.png}\"><BR>"
    echo "<IMG SRC=\"${file/%day.png/year.png}\"><BR>"
    echo "</FONT></P>"
done >>"$wwwdir/$indexhtm"
cat <<__EOT__ >>"$wwwdir/$indexhtm"
</BODY>
</HTML>
__EOT__

